name: Build
on:
  pull_request:
  push:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Install AWS CLI
      run: pip install --user awscli
    - name: Set up go
      uses: actions/setup-go@v3
      with:
        go-version: '>=1.19.0'
    - name: Install gostatic
      run: go install github.com/piranha/gostatic@latest
    - name: Build Blog
      run: gostatic config
    - name: Release
      if: github.ref == 'refs/heads/main'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-1
      run: aws s3 sync --delete build/ s3://akerl-littlesnitch/    - name: Post to hook-exporter
      run: ./.github/exporter.sh
      env:
        EXPORTER_TOKEN: ${{ secrets.EXPORTER_TOKEN }}
        JOB_STATUS: ${{ job.status }}
      if: ${{ always() }}
